version: "3.9"

services:
  psql:
    image: postgres:15
    container_name: co_psql
    ports:
      - "5433:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - ete_network

networks:
  ete_network:
    driver: bridge
    name: ete_network
